"""empty message

Revision ID: 064c429fa039
Revises: e95e0d82e25c
Create Date: 2020-05-12 09:07:34.490907

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = '064c429fa039'
down_revision = 'e95e0d82e25c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('finding_counter', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'vulnerability_counter')
    # ### end Alembic commands ###
