"""finding bugtracking

Revision ID: 13dc47d116fc
Revises: 81282ee00276
Create Date: 2020-10-14 09:05:43.522340

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = '13dc47d116fc'
down_revision = '81282ee00276'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finding', sa.Column('bugtracking', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###    
    op.drop_column('finding', 'bugtracking')
    # ### end Alembic commands ###
