"""Assessment: Risk Profile

Revision ID: 21eef33e8366
Revises: 68a62bb9bff4
Create Date: 2020-09-29 13:18:29.367458

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = '21eef33e8366'
down_revision = '68a62bb9bff4'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('riskprof_category', sarna.model.sql_types.enum.Enum(sarna.model.enums.riskprofile.RiskProfileType), nullable=False))
    op.add_column('assessment', sa.Column('riskprof_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment', 'riskprof_score')
    op.drop_column('assessment', 'riskprof_category')
    # ### end Alembic commands ###
