"""auditing

Revision ID: 29607c07f5f4
Revises: 2e3b5a7a4832
Create Date: 2021-01-07 13:33:21.118661

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '29607c07f5f4'
down_revision = '2e3b5a7a4832'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('user_type', sa.Integer(), nullable=False),
    sa.Column('source', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.String(length=50), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('otp_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_access', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_audit')
    # ### end Alembic commands ###
