"""delete unused finding fields

Revision ID: 2d9eec654165
Revises: 29607c07f5f4
Create Date: 2021-01-12 09:46:00.821574

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = '2d9eec654165'
down_revision = '29607c07f5f4'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finding', 'owisam_category')
    op.drop_column('finding', 'dissemination')
    op.drop_column('finding', 'solution_complexity')
    op.drop_column('finding', 'tech_risk')
    op.drop_column('finding', 'business_risk')
    op.drop_column('finding', 'exploitability')
    op.drop_column('finding_template', 'owisam_category')
    op.drop_column('finding_template', 'dissemination')
    op.drop_column('finding_template', 'solution_complexity')
    op.drop_column('finding_template', 'tech_risk')
    op.drop_column('finding_template', 'business_risk')
    op.drop_column('finding_template', 'exploitability')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finding_template', sa.Column('exploitability', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('finding_template', sa.Column('business_risk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('finding_template', sa.Column('tech_risk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('finding_template', sa.Column('solution_complexity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('finding_template', sa.Column('dissemination', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('finding_template', sa.Column('owisam_category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('finding', sa.Column('exploitability', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('finding', sa.Column('business_risk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('finding', sa.Column('tech_risk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('finding', sa.Column('solution_complexity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('finding', sa.Column('dissemination', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('finding', sa.Column('owisam_category', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
