"""Added 'notes' field to Finding table.

Revision ID: 3277e0ef1496
Revises: d0f2c1aa4cfd
Create Date: 2020-08-06 11:34:37.670537

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = '3277e0ef1496'
down_revision = 'd0f2c1aa4cfd'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finding', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finding', 'notes')
    # ### end Alembic commands ###
