"""assessment: sca+sast

Revision ID: 44c6c91dd3c4
Revises: 2a2c18ff68c6
Create Date: 2020-09-29 12:30:57.358608

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = '44c6c91dd3c4'
down_revision = '2a2c18ff68c6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('sast', sarna.model.sql_types.enum.Enum(sarna.model.enums.analysis.AnalysisResultType), nullable=False))
    op.add_column('assessment', sa.Column('sca', sarna.model.sql_types.enum.Enum(sarna.model.enums.analysis.AnalysisResultType), nullable=False))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment', 'sca')
    op.drop_column('assessment', 'sast')
    # ### end Alembic commands ###