"""empty message

Revision ID: 46155f63422c
Revises: 357612dfa45b
Create Date: 2018-07-20 05:00:35.859996

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = '46155f63422c'
down_revision = '357612dfa45b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finding', sa.Column('owasp_mobile_category', sarna.model.sql_types.enum.Enum(sarna.model.enums.category.OWASPMobileTop10Category), nullable=True))
    op.add_column('finding_template', sa.Column('owasp_mobile_category', sarna.model.sql_types.enum.Enum(sarna.model.enums.category.OWASPMobileTop10Category), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finding_template', 'owasp_mobile_category')
    op.drop_column('finding', 'owasp_mobile_category')
    # ### end Alembic commands ###
