"""empty message

Revision ID: 7436cae82ddd
Revises: e4ff87201e62
Create Date: 2018-06-29 04:04:04.758845

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = '7436cae82ddd'
down_revision = 'e4ff87201e62'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'finding', 'business_risk',
        existing_type=sa.INTEGER(),
        nullable=False,
        server_default='1'
    )
    op.alter_column(
        'finding', 'exploitability',
        existing_type=sa.INTEGER(),
        nullable=False,
        server_default='1'
    )
    op.add_column('finding_template', sa.Column('business_risk', sarna.model.sql_types.enum.Enum(sarna.model.enumerations.Score), nullable=False, server_default='1'))
    op.add_column('finding_template', sa.Column('exploitability', sarna.model.sql_types.enum.Enum(sarna.model.enumerations.Score), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finding_template', 'exploitability')
    op.drop_column('finding_template', 'business_risk')
    op.alter_column('finding', 'exploitability',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('finding', 'business_risk',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
