"""CWE

Revision ID: 81282ee00276
Revises: 21eef33e8366
Create Date: 2020-10-05 11:26:02.075780

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = '81282ee00276'
down_revision = '21eef33e8366'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finding', sa.Column('cwe', sarna.model.sql_types.enum.Enum(sarna.model.enums.category.CWE), nullable=False))
    op.add_column('finding_template', sa.Column('cwe', sarna.model.sql_types.enum.Enum(sarna.model.enums.category.CWE), nullable=False))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finding_template', 'cwe')
    op.drop_column('finding', 'cwe')
    # ### end Alembic commands ###
