"""empty message

Revision ID: 8abb844b1c27
Revises: d0d60a20bf61
Create Date: 2020-03-30 01:15:26.217750

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = '8abb844b1c27'
down_revision = 'd0d60a20bf61'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finding_template', sa.Column('cvss_v3_score', sa.Float(), nullable=False, server_default="0"))
    op.add_column('finding_template', sa.Column('cvss_v3_vector', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finding_template', 'cvss_v3_vector')
    op.drop_column('finding_template', 'cvss_v3_score')
    # ### end Alembic commands ###
