"""empty message

Revision ID: 951b8ed9a8e1
Revises: 9ab3158991e2
Create Date: 2020-05-12 09:53:12.043249

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = '951b8ed9a8e1'
down_revision = '9ab3158991e2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###

    from sarna.model.client import Client
    from sarna.model import db

    db.session.commit()

    for client in Client.query.all():
        for assessment in client.assessments:
            for finding in assessment.findings:
                finding.client_finding_id = client.generate_finding_counter()

    db.session.commit()

    op.alter_column('finding', 'client_finding_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finding', 'client_finding_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
