"""empty message

Revision ID: 9ab3158991e2
Revises: 064c429fa039
Create Date: 2020-05-12 09:52:45.826580

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = '9ab3158991e2'
down_revision = '064c429fa039'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finding', sa.Column('client_finding_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finding', 'client_finding_id')
    # ### end Alembic commands ###
