"""empty message

Revision ID: b434e5dc23d1
Revises: 7436cae82ddd
Create Date: 2018-07-01 17:11:32.641676

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = 'b434e5dc23d1'
down_revision = '7436cae82ddd'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sarna.model.sql_types.enum.Enum(sarna.model.enumerations.AccountType), nullable=False, server_default='1'))
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###
