"""empty message

Revision ID: d0d60a20bf61
Revises: 46155f63422c
Create Date: 2020-03-25 20:58:49.367271

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = 'd0d60a20bf61'
down_revision = '46155f63422c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finding', sa.Column('cvss_v3_score', sa.Float(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finding', 'cvss_v3_score')
    # ### end Alembic commands ###
