"""empty message

Revision ID: e4ff87201e62
Revises: e313aa147450
Create Date: 2018-06-28 23:09:05.401047

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = 'e4ff87201e62'
down_revision = 'e313aa147450'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('source', sarna.model.sql_types.enum.Enum(sarna.model.enumerations.AuthSource), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'source')
    # ### end Alembic commands ###
