"""empty message

Revision ID: e723103265ff
Revises: 
Create Date: 2018-06-24 18:11:46.288343

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = 'e723103265ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('passwd', sa.String(length=128), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('last_access', sa.DateTime(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('otp_enabled', sa.Boolean(), nullable=False),
    sa.Column('otp_seed', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=False),
    sa.Column('long_name', sa.String(length=128), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finding_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('Web', 'Infra', 'Config', name='findingtype'), nullable=False),
    sa.Column('owasp_category', sa.Enum('OTG_INFO_001', 'OTG_INFO_002', 'OTG_INFO_003', 'OTG_INFO_004', 'OTG_INFO_005', 'OTG_INFO_006', 'OTG_INFO_007', 'OTG_INFO_008', 'OTG_INFO_009', 'OTG_INFO_010', 'OTG_CONFIG_001', 'OTG_CONFIG_002', 'OTG_CONFIG_003', 'OTG_CONFIG_004', 'OTG_CONFIG_005', 'OTG_CONFIG_006', 'OTG_CONFIG_007', 'OTG_CONFIG_008', 'OTG_IDENT_001', 'OTG_IDENT_002', 'OTG_IDENT_003', 'OTG_IDENT_004', 'OTG_IDENT_005', 'OTG_IDENT_006', 'OTG_IDENT_007', 'OTG_AUTHN_001', 'OTG_AUTHN_002', 'OTG_AUTHN_003', 'OTG_AUTHN_004', 'OTG_AUTHN_005', 'OTG_AUTHN_006', 'OTG_AUTHN_007', 'OTG_AUTHN_008', 'OTG_AUTHN_009', 'OTG_AUTHN_010', 'OTG_AUTHZ_001', 'OTG_AUTHZ_002', 'OTG_AUTHZ_003', 'OTG_AUTHZ_004', 'OTG_SESS_001', 'OTG_SESS_002', 'OTG_SESS_003', 'OTG_SESS_004', 'OTG_SESS_005', 'OTG_SESS_006', 'OTG_SESS_007', 'OTG_SESS_008', 'OTG_INPVAL_001', 'OTG_INPVAL_002', 'OTG_INPVAL_003', 'OTG_INPVAL_004', 'OTG_INPVAL_005', 'OTG_INPVAL_006', 'OTG_INPVAL_007', 'OTG_INPVAL_008', 'OTG_INPVAL_009', 'OTG_INPVAL_010', 'OTG_INPVAL_011', 'OTG_INPVAL_012', 'OTG_INPVAL_013', 'OTG_INPVAL_014', 'OTG_INPVAL_015', 'OTG_INPVAL_016', 'OTG_ERR_001', 'OTG_ERR_002', 'OTG_CRYPST_001', 'OTG_CRYPST_002', 'OTG_CRYPST_003', 'OTG_BUSLOGIC_001', 'OTG_BUSLOGIC_002', 'OTG_BUSLOGIC_003', 'OTG_BUSLOGIC_004', 'OTG_BUSLOGIC_005', 'OTG_BUSLOGIC_006', 'OTG_BUSLOGIC_007', 'OTG_BUSLOGIC_008', 'OTG_BUSLOGIC_009', 'OTG_CLIENT_001', 'OTG_CLIENT_002', 'OTG_CLIENT_003', 'OTG_CLIENT_004', 'OTG_CLIENT_005', 'OTG_CLIENT_006', 'OTG_CLIENT_007', 'OTG_CLIENT_008', 'OTG_CLIENT_009', 'OTG_CLIENT_010', 'OTG_CLIENT_011', 'OTG_CLIENT_012', name='owaspcategory'), nullable=True),
    sa.Column('tech_risk', sa.Enum('Info', 'Low', 'Medium', 'High', 'Critical', 'NA', name='score'), nullable=False),
    sa.Column('dissemination', sa.Enum('Info', 'Low', 'Medium', 'High', 'Critical', 'NA', name='score'), nullable=False),
    sa.Column('solution_complexity', sa.Enum('Info', 'Low', 'Medium', 'High', 'Critical', 'NA', name='score'), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sarna.model.guid.GUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('lang', sa.Enum('Spanish', 'English', name='language'), nullable=False),
    sa.Column('type', sa.Enum('Web', 'External_pentest', 'Mobile', 'iOS', 'Android', 'WiFi', name='assessmenttype'), nullable=False),
    sa.Column('status', sa.Enum('Open', 'Closed', 'Archived', name='assessmentstatus'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('effective_hours', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('client_audit',
    sa.Column('audited_client_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audited_client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['auditor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('audited_client_id', 'auditor_id')
    )
    op.create_table('client_management',
    sa.Column('managed_client_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['managed_client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('managed_client_id', 'manager_id')
    )
    op.create_table('finding_template_translation',
    sa.Column('lang', sa.Enum('Spanish', 'English', name='language'), nullable=False),
    sa.Column('finding_template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('definition', sa.String(), nullable=False),
    sa.Column('references', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['finding_template_id'], ['finding_template.id'], ),
    sa.PrimaryKeyConstraint('lang', 'finding_template_id')
    )
    op.create_table('solution',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('finding_template_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Enum('Spanish', 'English', name='language'), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['finding_template_id'], ['finding_template.id'], ),
    sa.PrimaryKeyConstraint('name', 'finding_template_id')
    )
    op.create_table('template',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('file', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('name', 'client_id')
    )
    op.create_table('active',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'name')
    )
    op.create_table('assessment_audit',
    sa.Column('audited_assessment_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audited_assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['auditor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('audited_assessment_id', 'auditor_id')
    )
    op.create_table('auditor_approval',
    sa.Column('approving_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_assessment_id', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['approving_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('approving_user_id', 'approved_assessment_id')
    )
    op.create_table('finding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('Web', 'Infra', 'Config', name='findingtype'), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Reviewed', 'Confirmed', 'False_Positive', 'Other', name='findingstatus'), nullable=False),
    sa.Column('owasp_category', sa.Enum('OTG_INFO_001', 'OTG_INFO_002', 'OTG_INFO_003', 'OTG_INFO_004', 'OTG_INFO_005', 'OTG_INFO_006', 'OTG_INFO_007', 'OTG_INFO_008', 'OTG_INFO_009', 'OTG_INFO_010', 'OTG_CONFIG_001', 'OTG_CONFIG_002', 'OTG_CONFIG_003', 'OTG_CONFIG_004', 'OTG_CONFIG_005', 'OTG_CONFIG_006', 'OTG_CONFIG_007', 'OTG_CONFIG_008', 'OTG_IDENT_001', 'OTG_IDENT_002', 'OTG_IDENT_003', 'OTG_IDENT_004', 'OTG_IDENT_005', 'OTG_IDENT_006', 'OTG_IDENT_007', 'OTG_AUTHN_001', 'OTG_AUTHN_002', 'OTG_AUTHN_003', 'OTG_AUTHN_004', 'OTG_AUTHN_005', 'OTG_AUTHN_006', 'OTG_AUTHN_007', 'OTG_AUTHN_008', 'OTG_AUTHN_009', 'OTG_AUTHN_010', 'OTG_AUTHZ_001', 'OTG_AUTHZ_002', 'OTG_AUTHZ_003', 'OTG_AUTHZ_004', 'OTG_SESS_001', 'OTG_SESS_002', 'OTG_SESS_003', 'OTG_SESS_004', 'OTG_SESS_005', 'OTG_SESS_006', 'OTG_SESS_007', 'OTG_SESS_008', 'OTG_INPVAL_001', 'OTG_INPVAL_002', 'OTG_INPVAL_003', 'OTG_INPVAL_004', 'OTG_INPVAL_005', 'OTG_INPVAL_006', 'OTG_INPVAL_007', 'OTG_INPVAL_008', 'OTG_INPVAL_009', 'OTG_INPVAL_010', 'OTG_INPVAL_011', 'OTG_INPVAL_012', 'OTG_INPVAL_013', 'OTG_INPVAL_014', 'OTG_INPVAL_015', 'OTG_INPVAL_016', 'OTG_ERR_001', 'OTG_ERR_002', 'OTG_CRYPST_001', 'OTG_CRYPST_002', 'OTG_CRYPST_003', 'OTG_BUSLOGIC_001', 'OTG_BUSLOGIC_002', 'OTG_BUSLOGIC_003', 'OTG_BUSLOGIC_004', 'OTG_BUSLOGIC_005', 'OTG_BUSLOGIC_006', 'OTG_BUSLOGIC_007', 'OTG_BUSLOGIC_008', 'OTG_BUSLOGIC_009', 'OTG_CLIENT_001', 'OTG_CLIENT_002', 'OTG_CLIENT_003', 'OTG_CLIENT_004', 'OTG_CLIENT_005', 'OTG_CLIENT_006', 'OTG_CLIENT_007', 'OTG_CLIENT_008', 'OTG_CLIENT_009', 'OTG_CLIENT_010', 'OTG_CLIENT_011', 'OTG_CLIENT_012', name='owaspcategory'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('solution', sa.String(), nullable=True),
    sa.Column('tech_risk', sa.Enum('Info', 'Low', 'Medium', 'High', 'Critical', 'NA', name='score'), nullable=False),
    sa.Column('business_risk', sa.Enum('Info', 'Low', 'Medium', 'High', 'Critical', 'NA', name='score'), nullable=True),
    sa.Column('exploitability', sa.Enum('Info', 'Low', 'Medium', 'High', 'Critical', 'NA', name='score'), nullable=True),
    sa.Column('dissemination', sa.Enum('Info', 'Low', 'Medium', 'High', 'Critical', 'NA', name='score'), nullable=False),
    sa.Column('solution_complexity', sa.Enum('Info', 'Low', 'Medium', 'High', 'Critical', 'NA', name='score'), nullable=False),
    sa.Column('definition', sa.String(), nullable=False),
    sa.Column('references', sa.String(), nullable=False),
    sa.Column('cvss_v3_vector', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['finding_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('name', 'assessment_id')
    )
    op.create_table('affected_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_id', sa.Integer(), nullable=True),
    sa.Column('route', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['active_id'], ['active.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_id', 'route')
    )
    op.create_table('finding_affected_resource',
    sa.Column('affected_resource_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['affected_resource_id'], ['affected_resource.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.PrimaryKeyConstraint('affected_resource_id', 'finding_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finding_affected_resource')
    op.drop_table('affected_resource')
    op.drop_table('image')
    op.drop_table('finding')
    op.drop_table('auditor_approval')
    op.drop_table('assessment_audit')
    op.drop_table('active')
    op.drop_table('template')
    op.drop_table('solution')
    op.drop_table('finding_template_translation')
    op.drop_table('client_management')
    op.drop_table('client_audit')
    op.drop_table('assessment')
    op.drop_table('finding_template')
    op.drop_table('client')
    op.drop_table('user')
    # ### end Alembic commands ###
