"""finding: asvs + masvs

Revision ID: f82048e51f97
Revises: 3277e0ef1496
Create Date: 2020-09-29 10:19:36.507193

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = 'f82048e51f97'
down_revision = '3277e0ef1496'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finding', sa.Column('asvs', sa.String(length=8), nullable=True))
    op.add_column('finding', sa.Column('masvs', sa.String(length=8), nullable=True))
    op.add_column('finding_template', sa.Column('asvs', sa.String(length=8), nullable=True))
    op.add_column('finding_template', sa.Column('masvs', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finding', 'masvs')
    op.drop_column('finding', 'asvs')
    op.drop_column('finding_template', 'masvs')
    op.drop_column('finding_template', 'asvs')
    # ### end Alembic commands ###
